### ISSUE TITLE
Problem when openssl rand is used

### ISSUE THREAD

**Issue by kay0u** [YunoHost-Apps/plume_ynh#27]
Hi,

On the forum someone have an issue probably due to the use of openssl.

https://github.com/YunoHost-Apps/plume_ynh/blob/93e160532c585aa0c1533b922b4340a6f74d33fd/scripts/install#L36

I suggest to use `ynh_string_random 32` instead. (Need to be tested, maybe plume absolutely need an openssl rand?...)

You can find the topic here: https://forum.yunohost.org/t/installation-de-plume/7235

**Comment by elegaanz** [comment]
As long as it is a valid base-64 string, it should be good I think.

**Comment by yalh76** [comment]
@kay0u, i've tested to generate the secret_key with ynh_string_random instead of openssl
But without success

https://github.com/YunoHost-Apps/plume_ynh/commit/fe21bf96c8d637432efa07c93f9729bd5ac4092d

I keep the issue open to test ynh_string_random another time

**Comment by yalh76** [comment]
I tested to replace `secret_key=$(openssl rand -base64 32) ` by `ynh_string_random 32` `ynh_string_random 64` or `ynh_string_random 43` but plume service refuse to start because the secret_key wasn't good...

I have no solution for that.

And for the issue of https://forum.yunohost.org/t/installation-de-plume/7235, about openssl, I haven't enough competencies to solve his problem...

**Comment by yalh76** [comment]
Problem solved by @kay0u 

You can test the upgrade with: `yunohost app upgrade plume -u https://github.com/YunoHost-Apps/plume_ynh/tree/testing --debug`
